### PR TITLE
Fix for transactions

### LINKED ISSUE #256: Handle for change user's providerId
https://github.com/haqq-network/haqq-wallet/blob/main/src/screens/home-feed.tsx

In component HomeFeed  filtrate all transactions by providerId
current providerId provided in user model (useUser)

Testing:
change Provider in settings

### PR DESCRIPTION
**Pull request by gHashTag**
fix #256

### CODE REVIEW

File: src/screens/home-feed.tsx [hunk 1]
```diff
@@ -65,6 +66,12 @@ export const HomeFeedScreen = () => {
 
   useEffect(() => {}, [wallets]);
 
+  const filterTransactions = useCallback(() => {
+    return transactionsList.filter(
+      ({providerId}) => user.providerId === providerId,
+    );
+  }, [transactionsList, user.providerId])();
+
```
Comment (vivalaakam) [inline src/screens/home-feed.tsx:74]: Not solve problem, if we have operations for day X and have no operations in other network for these day, we saw header for day X

**Review by vivalaakam — CHANGES_REQUESTED** [review]
