### PR TITLE
refactor(StakingDelegate): fix flow problems

### LINKED ISSUE #457: [Staking] delegate pages
design:
* https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=3076%3A53074&t=o5QfEwHO2lQiONe5-4
* https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=3076%3A53174&t=o5QfEwHO2lQiONe5-4
* https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=3076%3A53214&t=o5QfEwHO2lQiONe5-4

### PR DESCRIPTION
**Pull request by gHashTag**
Fixes #457 

## Proposed Changes
- refactor screen
- fix operator_address mistake
- bottom sheet in staking-info
- title delegate change
- layout fix by design
- bottom sheet fix problem using with header

## Checklist

- [x] I have read the rules of [**contribution**](https://github.com/haqq-network/haqq-mobile/blob/main/docs/contribution.md#important-steps).

### CODE REVIEW

File: src/components/staking-delegate-form/staking-delegate-form.tsx [hunk 1]
```diff
@@ -72,7 +75,7 @@ export const StakingDelegateForm = ({
       <Button
         i18n={I18N.stakingDelegateFormPreview}
         style={styles.submit}
-        disabled={!amounts.isValid}
+        disabled={amounts.isValid}
```
Comment (vivalaakam) [inline src/components/staking-delegate-form/staking-delegate-form.tsx:78]: are you sure?

**Review by vivalaakam — APPROVED** [review]
