### PR TITLE
fix(SettingsAccountStyle): fix error with segmented select

### LINKED ISSUE #684: [SettingsAccountStyle]: fix selectors
Selectors on SettingsAccountStyle not working with initial data

Image
Image

### PR DESCRIPTION
**Pull request by vivalaakam**
Fixes #684 

## Proposed Changes

  - fix wallet default card style
  - fix texts

## Checklist

- [x] I have read the rules of [**contribution**](https://github.com/haqq-network/haqq-wallet/blob/main/docs/contribution.md#important-steps).

### CODE REVIEW

File: src/components/settings-account-style.tsx [hunk 1]
```diff
@@ -181,6 +177,8 @@ export const SettingsAccountStyle = ({
     },
     [setCardStyle, setColors],
   );
+  console.log('patternVariants', patternStyle, patternVariants);
```
Comment (gHashTag) [inline src/components/settings-account-style.tsx:180]: Hide please

**Review by gHashTag — APPROVED** [review]
